export const books = {
  reductionsItemBy50per: [
    {
      id: 1,
      idSection: "reductionsItemBy50per-1",
      name: "Clean Code",
      author: "Robert C. Martin",
      categories: ["Programming", "Software Engineering", "Best Practices"],
      priceInitial: 45.0,
      priceFinal: 35.99,
      isbn: "978-0132350884",
      publicationYear: 2008,
      language: "English",
      pages: 464,
      rating: 4.7,
      inStock: true,
      coverUrl: "/images/clean-code.jpg",
      quantity: 1
    },
    {
      id: 2,
      idSection: "reductionsItemBy50per-2",
      name: "The Pragmatic Programmer",
      author: "Andrew Hunt, David Thomas",
      categories: ["Programming", "Career", "Technology"],
      priceInitial: 50.0,
      priceFinal: 42.5,
      isbn: "978-0201616224",
      publicationYear: 1999,
      language: "English",
      pages: 352,
      rating: 4.8,
      inStock: true,
      coverUrl: "/images/pragmatic-programmer.jpg",
      quantity: 1
    },
    {
      id: 3,
      idSection: "reductionsItemBy50per-3",
      name: "Atomic Habits",
      author: "James Clear",
      categories: ["Self-Help", "Psychology", "Productivity"],
      priceInitial: 30.0,
      priceFinal: 21.99,
      isbn: "978-0735211292",
      publicationYear: 2018,
      language: "English",
      pages: 320,
      rating: 4.6,
      inStock: true,
      coverUrl: "/images/atomic-habits.jpg",
      quantity: 1
    },
    {
      id: 4,
      idSection: "reductionsItemBy50per-4",
      name: "1984",
      author: "George Orwell",
      categories: ["Fiction", "Dystopian", "Political"],
      priceInitial: 20.0,
      priceFinal: 14.99,
      isbn: "978-0451524935",
      publicationYear: 1949,
      language: "English",
      pages: 328,
      rating: 4.5,
      inStock: false,
      coverUrl: "/images/1984.jpg",
      quantity: 1
    },
    {
      id: 5,
      idSection: "reductionsItemBy50per-5",
      name: "Sapiens: A Brief History of Humankind",
      author: "Yuval Noah Harari",
      categories: ["History", "Science", "Anthropology"],
      priceInitial: 40.0,
      priceFinal: 32.0,
      isbn: "978-0062316097",
      publicationYear: 2011,
      language: "English",
      pages: 498,
      rating: 4.7,
      inStock: true,
      coverUrl: "/images/sapiens.jpg",
      quantity: 1
    },
    {
      id: 6,
      idSection: "reductionsItemBy50per-6",
      name: "Deep Work",
      author: "Cal Newport",
      categories: ["Productivity", "Self-Help", "Business"],
      priceInitial: 28.0,
      priceFinal: 19.99,
      isbn: "978-1455586691",
      publicationYear: 2016,
      language: "English",
      pages: 304,
      rating: 4.4,
      inStock: true,
      coverUrl: "/images/deep-work.jpg",
      quantity: 1
    },
    {
      id: 7,
      idSection: "reductionsItemBy50per-7",
      name: "The Hobbit",
      author: "J.R.R. Tolkien",
      categories: ["Fantasy", "Adventure", "Fiction"],
      priceInitial: 25.0,
      priceFinal: 18.5,
      isbn: "978-0547928227",
      publicationYear: 1937,
      language: "English",
      pages: 310,
      rating: 4.8,
      inStock: true,
      coverUrl: "/images/the-hobbit.jpg",
      quantity: 1
    }
  ],

  booksSection: [
    { id: 1, idBookSection: "products-1", name: "Dragon Tales", categories: ["Fantasie"], priceInitial: 25, priceFinal: 20, lastUpdate: "before week", quantity: 1 },
    { id: 2, idBookSection: "products-2", name: "Love in Paris", categories: ["Love", "Drama"], priceInitial: 30, priceFinal: 25, lastUpdate: "before month", quantity: 1 },
    { id: 3, idBookSection: "products-3", name: "Samurai Adventure", categories: ["Manga", "Fantasie"], priceInitial: 28, priceFinal: 22, lastUpdate: "before year", quantity: 1 },
    { id: 4, idBookSection: "products-4", name: "Manhwa Chronicles", categories: ["Manhwa"], priceInitial: 22, priceFinal: 18, lastUpdate: "before week", quantity: 1 },
    { id: 5, idBookSection: "products-5", name: "Romantic Sunset", categories: ["Love"], priceInitial: 18, priceFinal: 15, lastUpdate: "before month", quantity: 1 },
    { id: 6, idBookSection: "products-6", name: "Epic Fantasie World", categories: ["Fantasie", "Drama"], priceInitial: 35, priceFinal: 30, lastUpdate: "before year", quantity: 1 },
    { id: 7, idBookSection: "products-7", name: "Shoujo Dreams", categories: ["Manga", "Love"], priceInitial: 20, priceFinal: 16, lastUpdate: "before week", quantity: 1 },
    { id: 8, idBookSection: "products-8", name: "Mystery Manor", categories: ["Drama"], priceInitial: 25, priceFinal: 22, lastUpdate: "before month", quantity: 1 },
    { id: 9, idBookSection: "products-9", name: "Manhwa Legends", categories: ["Manhwa", "Fantasie"], priceInitial: 28, priceFinal: 24, lastUpdate: "before year", quantity: 1 },
    { id: 10, idBookSection: "products-10", name: "Love Story 101", categories: ["Love", "Drama"], priceInitial: 22, priceFinal: 18, lastUpdate: "before week", quantity: 1 }
  ],

  mangaBooks: [
    { id: 1, name: "One Piece", rating: 4.9, img: "", publicationYear: 1997, author: "Eiichiro Oda", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], quantity: 1 },
    { id: 2, name: "Naruto", rating: 4.8, img: "", publicationYear: 1999, author: "Masashi Kishimoto", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], quantity: 1 },
    { id: 3, name: "Black Clover", rating: 4.6, img: "", publicationYear: 2015, author: "Yūki Tabata", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], quantity: 1 },
    { id: 4, name: "Death Note", rating: 4.9, img: "", publicationYear: 2003, author: "Tsugumi Ohba", categories: ["Manga", "Mystery", "Psychological", "Supernatural", "Thriller"], quantity: 1 },
    { id: 5, name: "Hunter x Hunter", rating: 4.7, img: "", publicationYear: 1998, author: "Yoshihiro Togashi", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], quantity: 1 },
    { id: 6, name: "Demon Slayer (Kimetsu no Yaiba)", rating: 4.8, img: "", publicationYear: 2016, author: "Koyoharu Gotouge", categories: ["Manga", "Action", "Adventure", "Fantasy", "Shounen"], quantity: 1 },
    { id: 7, name: "That Time I Got Reincarnated as a Slime", rating: 4.7, img: "", publicationYear: 2013, author: "Fuse", categories: ["Manga", "Adventure", "Fantasy", "Isekai", "Action"], quantity: 1 }
  ],

  manhwaBooks: [
    { id: 1, name: "Solo Leveling", rating: 4.9, img: "", publicationYear: 2016, author: "Chugong", categories: ["Manhwa", "Action", "Adventure", "Fantasy"], quantity: 1 },
    { id: 2, name: "Noblesse", rating: 4.6, img: "", publicationYear: 2007, author: "Son Jeho", categories: ["Manhwa", "Action", "Supernatural", "Fantasy"], quantity: 1 },
    { id: 3, name: "The Beginning After The End", rating: 4.8, img: "", publicationYear: 2017, author: "TurtleMe", categories: ["Manhwa", "Fantasy", "Adventure", "Reincarnation"], quantity: 1 },
    { id: 4, name: "The Infinite Mage", rating: 4.5, img: "", publicationYear: 2023, author: "", categories: ["Manhwa", "Fantasy", "Adventure", "Magic"], quantity: 1 },
    { id: 5, name: "Villain to Kill", rating: 4.4, img: "", publicationYear: 2021, author: "", categories: ["Manhwa", "Action", "Thriller", "Adventure"], quantity: 1 }
  ]
};
