export const books = {
  reductionsItemBy50per: [
    {
      id: 1,
      idSection: "reductionsItemBy50per-1",
      name: "Clean Code",
      author: "Robert C. Martin",
      categories: ["Programming", "Software Engineering", "Best Practices"],
      priceInitial: 45.0,
      priceFinal: 35.99,
      isbn: "978-0132350884",
      publicationYear: 2008,
      language: "English",
      pages: 464,
      rating: 4.7,
      inStock: true,
      coverUrl: "/images/clean-code.jpg",
      quantity: 1
    },
    {
      id: 2,
      idSection: "reductionsItemBy50per-2",
      name: "The Pragmatic Programmer",
      author: "Andrew Hunt, David Thomas",
      categories: ["Programming", "Career", "Technology"],
      priceInitial: 50.0,
      priceFinal: 42.5,
      isbn: "978-0201616224",
      publicationYear: 1999,
      language: "English",
      pages: 352,
      rating: 4.8,
      inStock: true,
      coverUrl: "/images/pragmatic-programmer.jpg",
      quantity: 1
    },
    {
      id: 3,
      idSection: "reductionsItemBy50per-3",
      name: "Atomic Habits",
      author: "James Clear",
      categories: ["Self-Help", "Psychology", "Productivity"],
      priceInitial: 30.0,
      priceFinal: 21.99,
      isbn: "978-0735211292",
      publicationYear: 2018,
      language: "English",
      pages: 320,
      rating: 4.6,
      inStock: true,
      coverUrl: "/images/atomic-habits.jpg",
      quantity: 1
    },
    {
      id: 4,
      idSection: "reductionsItemBy50per-4",
      name: "1984",
      author: "George Orwell",
      categories: ["Fiction", "Dystopian", "Political"],
      priceInitial: 20.0,
      priceFinal: 14.99,
      isbn: "978-0451524935",
      publicationYear: 1949,
      language: "English",
      pages: 328,
      rating: 4.5,
      inStock: false,
      coverUrl: "/images/1984.jpg",
      quantity: 1
    },
    {
      id: 5,
      idSection: "reductionsItemBy50per-5",
      name: "Sapiens: A Brief History of Humankind",
      author: "Yuval Noah Harari",
      categories: ["History", "Science", "Anthropology"],
      priceInitial: 40.0,
      priceFinal: 32.0,
      isbn: "978-0062316097",
      publicationYear: 2011,
      language: "English",
      pages: 498,
      rating: 4.7,
      inStock: true,
      coverUrl: "/images/sapiens.jpg",
      quantity: 1
    },
    {
      id: 6,
      idSection: "reductionsItemBy50per-6",
      name: "Deep Work",
      author: "Cal Newport",
      categories: ["Productivity", "Self-Help", "Business"],
      priceInitial: 28.0,
      priceFinal: 19.99,
      isbn: "978-1455586691",
      publicationYear: 2016,
      language: "English",
      pages: 304,
      rating: 4.4,
      inStock: true,
      coverUrl: "/images/deep-work.jpg",
      quantity: 1
    },
    {
      id: 7,
      idSection: "reductionsItemBy50per-7",
      name: "The Hobbit",
      author: "J.R.R. Tolkien",
      categories: ["Fantasy", "Adventure", "Fiction"],
      priceInitial: 25.0,
      priceFinal: 18.5,
      isbn: "978-0547928227",
      publicationYear: 1937,
      language: "English",
      pages: 310,
      rating: 4.8,
      inStock: true,
      coverUrl: "/images/the-hobbit.jpg",
      quantity: 1
    }
  ],

  booksSection: [
    { id: 1, idSection: "products-1", name: "Dragon Tales", categories: ["Fantasie"], priceInitial: 25, priceFinal: 20, lastUpdate: "before week", quantity: 1 },
    { id: 2, idSection: "products-2", name: "Love in Paris", categories: ["Love", "Drama"], priceInitial: 30, priceFinal: 25, lastUpdate: "before month", quantity: 1 },
    { id: 3, idSection: "products-3", name: "Samurai Adventure", categories: ["Manga", "Fantasie"], priceInitial: 28, priceFinal: 22, lastUpdate: "before year", quantity: 1 },
    { id: 4, idSection: "products-4", name: "Manhwa Chronicles", categories: ["Manhwa"], priceInitial: 22, priceFinal: 18, lastUpdate: "before week", quantity: 1 },
    { id: 5, idSection: "products-5", name: "Romantic Sunset", categories: ["Love"], priceInitial: 18, priceFinal: 15, lastUpdate: "before month", quantity: 1 },
    { id: 6, idSection: "products-6", name: "Epic Fantasie World", categories: ["Fantasie", "Drama"], priceInitial: 35, priceFinal: 30, lastUpdate: "before year", quantity: 1 },
    { id: 7, idSection: "products-7", name: "Shoujo Dreams", categories: ["Manga", "Love"], priceInitial: 20, priceFinal: 16, lastUpdate: "before week", quantity: 1 },
    { id: 8, idSection: "products-8", name: "Mystery Manor", categories: ["Drama"], priceInitial: 25, priceFinal: 22, lastUpdate: "before month", quantity: 1 },
    { id: 9, idSection: "products-9", name: "Manhwa Legends", categories: ["Manhwa", "Fantasie"], priceInitial: 28, priceFinal: 24, lastUpdate: "before year", quantity: 1 },
    { id: 10, idSection: "products-10", name: "Love Story 101", categories: ["Love", "Drama"], priceInitial: 22, priceFinal: 18, lastUpdate: "before week", quantity: 1 }
  ],

mangaBooks: [
  { id: 1, idSection: "manga-1", name: "One Piece", rating: 4.9, image: "/imgs/manga-manhwa-section/manga/onePiece.jpg", publicationYear: 1997, author: "Eiichiro Oda", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], priceInitial: 30, priceFinal: 25, lastUpdate: "before week", quantity: 1 },
  { id: 2, idSection: "manga-2", name: "Naruto", rating: 4.8, image: "/imgs/manga-manhwa-section/manga/naruto.jpg", publicationYear: 1999, author: "Masashi Kishimoto", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], priceInitial: 28, priceFinal: 23, lastUpdate: "before month", quantity: 1 },
  { id: 3, idSection: "manga-3", name: "Black Clover", rating: 4.6, image: "/imgs/manga-manhwa-section/manga/blackClover.jpg", publicationYear: 2015, author: "Yūki Tabata", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], priceInitial: 26, priceFinal: 22, lastUpdate: "before year", quantity: 1 },
  { id: 4, idSection: "manga-4", name: "Death Note", rating: 4.9, image: "/imgs/manga-manhwa-section/manga/deadNote.webp", publicationYear: 2003, author: "Tsugumi Ohba", categories: ["Manga", "Mystery", "Psychological", "Supernatural", "Thriller"], priceInitial: 32, priceFinal: 27, lastUpdate: "before week", quantity: 1 },
  { id: 5, idSection: "manga-5", name: "Hunter x Hunter", rating: 4.7, image: "/imgs/manga-manhwa-section/manga/Hunter.jpg", publicationYear: 1998, author: "Yoshihiro Togashi", categories: ["Manga", "Adventure", "Action", "Fantasy", "Shounen"], priceInitial: 29, priceFinal: 24, lastUpdate: "before month", quantity: 1 },
  { id: 6, idSection: "manga-6", name: "Demon Slayer", rating: 4.8, image: "/imgs/manga-manhwa-section/manga/kimetsu.jpg", publicationYear: 2016, author: "Koyoharu Gotouge", categories: ["Manga", "Action", "Adventure", "Fantasy", "Shounen"], priceInitial: 31, priceFinal: 26, lastUpdate: "before year", quantity: 1 },
  { id: 7, idSection: "manga-7", name: "That Time I Got Reincarnated as a Slime", rating: 4.7, image: "/imgs/manga-manhwa-section/manga/tenseiSlime.jpg", publicationYear: 2013, author: "Fuse", categories: ["Manga", "Adventure", "Fantasy", "Isekai", "Action"], priceInitial: 27, priceFinal: 22, lastUpdate: "before week", quantity: 1 }
],

manhwaBooks: [
  { id: 1, idSection: "manhwa-1", name: "Solo Leveling", rating: 4.9, image: "/imgs/manga-manhwa-section/manhwa/soloLeveling.jpg", publicationYear: 2016, author: "Chugong", categories: ["Manhwa", "Action", "Adventure", "Fantasy"], priceInitial: 28, priceFinal: 23, lastUpdate: "before week", quantity: 1 },
  { id: 2, idSection: "manhwa-2", name: "Noblesse", rating: 4.6, image: "/imgs/manga-manhwa-section/manhwa/nobless.jpg", publicationYear: 2007, author: "Son Jeho", categories: ["Manhwa", "Action", "Supernatural", "Fantasy"], priceInitial: 26, priceFinal: 21, lastUpdate: "before month", quantity: 1 },
  { id: 3, idSection: "manhwa-3", name: "The Beginning After The End", rating: 4.8, image: "/imgs/manga-manhwa-section/manhwa/theBeginnigAfterTheEnd.jpg", publicationYear: 2017, author: "TurtleMe", categories: ["Manhwa", "Fantasy", "Adventure", "Reincarnation"], priceInitial: 30, priceFinal: 25, lastUpdate: "before year", quantity: 1 },
  { id: 4, idSection: "manhwa-4", name: "The Infinite Mage", rating: 4.5, image: "/imgs/manga-manhwa-section/manhwa/TheInfiniteMage.jpg", publicationYear: 2023, author: "", categories: ["Manhwa", "Fantasy", "Adventure", "Magic"], priceInitial: 24, priceFinal: 20, lastUpdate: "before week", quantity: 1 },
  { id: 5, idSection: "manhwa-5", name: "Villain to Kill", rating: 4.4, image: "/imgs/manga-manhwa-section/manhwa/villainToKill.jpg", publicationYear: 2021, author: "", categories: ["Manhwa", "Action", "Thriller", "Adventure"], priceInitial: 23, priceFinal: 19, lastUpdate: "before month", quantity: 1 }
],

 fantasyCategorie:[
  {
    id: 1,
    idSection: "fantasy-1",
    name: "Assassin's Academy",
    author: "Jeff Brown",
    categories: ["Fantasy", "YA"],
    priceInitial: 32,
    priceFinal: 26,
    lastUpdate: "before week",
    quantity: 1,
    image: "assassinsacademy_jeffbrown_ya_fantasy.webp"
  },
  {
    id: 2,
    idSection: "fantasy-2",
    name: "Breaking the Ice",
    author: "Jeff Brown",
    categories: ["Fantasy", "Adventure"],
    priceInitial: 28,
    priceFinal: 22,
    lastUpdate: "before month",
    quantity: 1,
    image: "BreakingTheIce.jpg"
  },
  {
    id: 3,
    idSection: "fantasy-3",
    name: "Curse of Shadows",
    author: "Jeff Brown",
    categories: ["Fantasy", "Dark Fantasy"],
    priceInitial: 35,
    priceFinal: 29,
    lastUpdate: "before week",
    quantity: 1,
    image: "CurseOfShadows.jpg"
  },
  {
    id: 4,
    idSection: "fantasy-4",
    name: "Flames of Gold",
    author: "Jeff Brown",
    categories: ["Fantasy", "Epic"],
    priceInitial: 38,
    priceFinal: 32,
    lastUpdate: "before year",
    quantity: 1,
    image: "flamesofgold_jeffbrown_bookcover.webp"
  },
  {
    id: 5,
    idSection: "fantasy-5",
    name: "Lurid Curse",
    author: "Jeff Brown",
    categories: ["Fantasy", "Mystery"],
    priceInitial: 30,
    priceFinal: 24,
    lastUpdate: "before month",
    quantity: 1,
    image: "luridcurse.webp"
  },
  {
    id: 6,
    idSection: "fantasy-6",
    name: "Seam of Eternity",
    author: "Jeff Brown",
    categories: ["Fantasy", "High Fantasy"],
    priceInitial: 40,
    priceFinal: 34,
    lastUpdate: "before year",
    quantity: 1,
    image: "seamofeternity_fantasybookcover_jeffbrown.webp"
  },
  {
    id: 7,
    idSection: "fantasy-7",
    name: "The Witcher",
    author: "Andrzej Sapkowski",
    categories: ["Fantasy", "Dark Fantasy"],
    priceInitial: 45,
    priceFinal: 38,
    lastUpdate: "before week",
    quantity: 1,
    image: "theWitcher.jpg"
  },
  {
    id: 8,
    idSection: "fantasy-8",
    name: "Winds of Change",
    author: "Jeff Brown",
    categories: ["Fantasy", "Adventure"],
    priceInitial: 34,
    priceFinal: 28,
    lastUpdate: "before month",
    quantity: 1,
    image: "windsofchange_ebook_jeffbrown.webp"
  }
]

};
