export const products = [
  { id: 1, name: "Dragon Tales", categories: ["Fantasie"], priceInitial: 25, priceFinal: 20, lastUpdate: "before week" },
  { id: 2, name: "Love in Paris", categories: ["Love", "Drama"], priceInitial: 30, priceFinal: 25, lastUpdate: "before month" },
  { id: 3, name: "Samurai Adventure", categories: ["Manga", "Fantasie"], priceInitial: 28, priceFinal: 22, lastUpdate: "before year" },
  { id: 4, name: "Manhwa Chronicles", categories: ["Manhwa"], priceInitial: 22, priceFinal: 18, lastUpdate: "before week" },
  { id: 5, name: "Romantic Sunset", categories: ["Love"], priceInitial: 18, priceFinal: 15, lastUpdate: "before month" },
  { id: 6, name: "Epic Fantasie World", categories: ["Fantasie", "Drama"], priceInitial: 35, priceFinal: 30, lastUpdate: "before year" },
  { id: 7, name: "Shoujo Dreams", categories: ["Manga", "Love"], priceInitial: 20, priceFinal: 16, lastUpdate: "before week" },
  { id: 8, name: "Mystery Manor", categories: ["Drama"], priceInitial: 25, priceFinal: 22, lastUpdate: "before month" },
  { id: 9, name: "Manhwa Legends", categories: ["Manhwa", "Fantasie"], priceInitial: 28, priceFinal: 24, lastUpdate: "before year" },
  { id: 10, name: "Love Story 101", categories: ["Love", "Drama"], priceInitial: 22, priceFinal: 18, lastUpdate: "before week" },
  { id: 11, name: "Fantasie Quest", categories: ["Fantasie"], priceInitial: 27, priceFinal: 23, lastUpdate: "before month" },
  { id: 12, name: "Manga Legends", categories: ["Manga"], priceInitial: 24, priceFinal: 20, lastUpdate: "before year" },
  { id: 13, name: "Romance in Bloom", categories: ["Love"], priceInitial: 19, priceFinal: 15, lastUpdate: "before week" },
  { id: 14, name: "Drama Nights", categories: ["Drama"], priceInitial: 26, priceFinal: 22, lastUpdate: "before month" },
  { id: 15, name: "Manhwa Adventures", categories: ["Manhwa"], priceInitial: 23, priceFinal: 19, lastUpdate: "before year" },
  { id: 16, name: "Fantasy Heroes", categories: ["Fantasie"], priceInitial: 30, priceFinal: 25, lastUpdate: "before week" },
  { id: 17, name: "Manga World", categories: ["Manga"], priceInitial: 22, priceFinal: 18, lastUpdate: "before month" },
  { id: 18, name: "Love in Tokyo", categories: ["Love"], priceInitial: 20, priceFinal: 16, lastUpdate: "before year" },
  { id: 19, name: "Drama Kings", categories: ["Drama"], priceInitial: 28, priceFinal: 23, lastUpdate: "before week" },
  { id: 20, name: "Manhwa Secrets", categories: ["Manhwa"], priceInitial: 25, priceFinal: 21, lastUpdate: "before month" },
  { id: 21, name: "Fantasie Realm", categories: ["Fantasie"], priceInitial: 32, priceFinal: 28, lastUpdate: "before year" },
  { id: 22, name: "Romantic Escape", categories: ["Love"], priceInitial: 18, priceFinal: 15, lastUpdate: "before week" },
  { id: 23, name: "Manga Dreams", categories: ["Manga", "Love"], priceInitial: 24, priceFinal: 20, lastUpdate: "before month" },
  { id: 24, name: "Drama Queen", categories: ["Drama"], priceInitial: 27, priceFinal: 22, lastUpdate: "before year" },
  { id: 25, name: "Manhwa Tales", categories: ["Manhwa"], priceInitial: 23, priceFinal: 19, lastUpdate: "before week" },
  { id: 26, name: "Fantasie Kingdom", categories: ["Fantasie"], priceInitial: 35, priceFinal: 30, lastUpdate: "before month" },
  { id: 27, name: "Love Horizon", categories: ["Love"], priceInitial: 21, priceFinal: 17, lastUpdate: "before year" },
  { id: 28, name: "Manga Saga", categories: ["Manga"], priceInitial: 26, priceFinal: 22, lastUpdate: "before week" },
  { id: 29, name: "Drama Tales", categories: ["Drama"], priceInitial: 29, priceFinal: 24, lastUpdate: "before month" },
  { id: 30, name: "Manhwa Chronicles II", categories: ["Manhwa"], priceInitial: 24, priceFinal: 20, lastUpdate: "before year" },
  { id: 31, name: "Fantasy Legends", categories: ["Fantasie"], priceInitial: 30, priceFinal: 25, lastUpdate: "before week" },
  { id: 32, name: "Love in Moonlight", categories: ["Love"], priceInitial: 19, priceFinal: 16, lastUpdate: "before month" },
  { id: 33, name: "Manga Adventure II", categories: ["Manga"], priceInitial: 25, priceFinal: 21, lastUpdate: "before year" },
  { id: 34, name: "Drama Nights II", categories: ["Drama"], priceInitial: 28, priceFinal: 23, lastUpdate: "before week" },
  { id: 35, name: "Manhwa Heroes", categories: ["Manhwa"], priceInitial: 23, priceFinal: 19, lastUpdate: "before month" },
  { id: 36, name: "Fantasie World II", categories: ["Fantasie"], priceInitial: 33, priceFinal: 28, lastUpdate: "before year" },
  { id: 37, name: "Romantic Moon", categories: ["Love"], priceInitial: 18, priceFinal: 15, lastUpdate: "before week" },
  { id: 38, name: "Manga Legends II", categories: ["Manga"], priceInitial: 24, priceFinal: 20, lastUpdate: "before month" },
  { id: 39, name: "Drama Saga", categories: ["Drama"], priceInitial: 27, priceFinal: 23, lastUpdate: "before year" },
  { id: 40, name: "Manhwa Secrets II", categories: ["Manhwa"], priceInitial: 26, priceFinal: 22, lastUpdate: "before week" },
  { id: 41, name: "Fantasie Heroes II", categories: ["Fantasie"], priceInitial: 32, priceFinal: 28, lastUpdate: "before month" },
  { id: 42, name: "Love Horizon II", categories: ["Love"], priceInitial: 20, priceFinal: 17, lastUpdate: "before year" },
  { id: 43, name: "Manga Quest", categories: ["Manga"], priceInitial: 26, priceFinal: 22, lastUpdate: "before week" },
  { id: 44, name: "Drama Legends II", categories: ["Drama"], priceInitial: 29, priceFinal: 25, lastUpdate: "before month" },
  { id: 45, name: "Manhwa Tales II", categories: ["Manhwa"], priceInitial: 24, priceFinal: 20, lastUpdate: "before year" },
  { id: 46, name: "Fantasie Quest II", categories: ["Fantasie"], priceInitial: 30, priceFinal: 26, lastUpdate: "before week" },
  { id: 47, name: "Love in Stars", categories: ["Love"], priceInitial: 19, priceFinal: 16, lastUpdate: "before month" },
  { id: 48, name: "Manga Saga II", categories: ["Manga"], priceInitial: 25, priceFinal: 21, lastUpdate: "before year" },
  { id: 49, name: "Drama Nights III", categories: ["Drama"], priceInitial: 28, priceFinal: 24, lastUpdate: "before week" },
  { id: 50, name: "Manhwa Heroes II", categories: ["Manhwa"], priceInitial: 27, priceFinal: 22, lastUpdate: "before month" }
];
